project:
  name: sdp-kafka
  regions:
    - eu-west-1

tests:
  default:
    parameters:
      QSS3BucketName: $[taskcat_autobucket]
      EnvironmentName: $[taskcat_genpass_8]
    template: ./templates/streaming-platform.template

